version: '3.4'

services:
  busservices.buses.api:
    image: ${DOCKER_REGISTRY-}busservicesbusesapi
    build:
      context: .
      dockerfile: BusServices.Buses.Api/Dockerfile
    depends_on:
      - rabbitmq
      - mongo

  busservices.scheduling.worker:
    image: ${DOCKER_REGISTRY-}busservicesschedulingworker
    build:
      context: .
      dockerfile: BusServices.Scheduling.Worker/Dockerfile
    depends_on:
      - rabbitmq
      - mongo
  
  rabbitmq:
    image: "rabbitmq:3.8-management"

  mongo:
    image: mongo:latest

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
  
volumes:
  mongodb_data_container: